#!/usr/bin/env sh
# do not manage the following apps
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^aText$" manage=off
yabai -m rule --add app="^AppCleaner$" manage=off
# float all preferences windows
yabai -m rule --add title='Preferences$' manage=off topmost=on

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config window_placement second_child
yabai -m config window_border off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   10

yabai -m rule --add app="Chrome" space=1
yabai -m rule --add app="Firefox" space=1
yabai -m rule --add app="Preview" space=1

yabai -m rule --add app="Code" space=2
yabai -m rule --add app="iTerm" space=2

# yabai -m rule --add app="WhatsApp" space=3
yabai -m rule --add app="Mail" space=3
yabai -m rule --add app="Slack" space=3

killall limelight &>/dev/null
limelight &>/dev/null &

echo "yabai configuration loaded.."

