if [[ $(hostname) =~ .*Book.* ]]; then
  echo "==> on mac"
  alias ls="ls -G"
  export LSCOLORS=Exfxcxdxbxegedabagacad
  export PATH="$PATH:$(pwd)"
elif [[ $(hostname) =~ .*fkreuk.* ]]; then
  echo "==> on nv local machine"
  alias ngc=$HOME/installations/ngc
  alias gpustat=/home/tlv/.local/bin/gpustat
else
  echo "==> on lab cluster machine"
  alias nvim=$HOME/installations/nvim.appimage
  alias bat=$HOME/installations/bat/bat
  alias vifm=$HOME/installations/vifm/bin/vifm
  alias ts=$HOME/installations/ts/ts
  alias ack='~/installations/ack'
  PATH=$HOME/anaconda3/bin:$PATH
  export EDITOR=$HOME/installations/nvim.appimage
  export GIT_EDITOR=$HOME/installations/nvim.appimage
  alias ls="ls --color=always"
  export LS_COLORS="di=1;34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43" # match colors with mac ls
fi

export LANG=en_US.utf8
export LC_ALL=en_US.utf8
export DOTFILES=$HOME/.dotfiles
export ZSH=$HOME/.oh-my-zsh
export PATH=$HOME/local/bin:$PATH

ZSH_THEME="typewritten"
HISTSIZE=1000
SAVEHIST=1000
plugins=(
    zsh-autosuggestions
    git
    zsh-syntax-highlighting
    tmux
    web-search
)

source $ZSH/oh-my-zsh.sh
source $DOTFILES/zsh/aliases.zsh
source $DOTFILES/zsh/ts.zsh
source $DOTFILES/zsh/conda.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/felixkreuk/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/felixkreuk/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/felixkreuk/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/felixkreuk/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

