if [[ $(whoami) =~ felixkreuk ]]; then
  echo "==> on mac"
  # ruby stuff for jekyll
  export PATH="/usr/local/opt/ruby/bin:$PATH"
  export PATH="$HOME/.gem/ruby/2.7.0/bin:$PATH"

elif [[ $(hostname) =~ .*fkreuk.* ]]; then
  echo "==> on nv local machine"
  alias ngc=$HOME/installations/ngc
  alias gpustat=/home/tlv/.local/bin/gpustat
  alias ngrok=/home/tlv/installations/ngrok
  PATH="$PATH:/home/tlv/.local/bin"

else
  echo "==> on lab cluster machine"
  alias ls="ls --color=always"
  alias nvim=nvim.appimage
  export EDITOR=$HOME/installations/nvim.appimage
  export GIT_EDITOR=$HOME/installations/nvim.appimage
  export LS_COLORS="di=1;34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43" # match colors with mac ls
  PATH=$HOME/anaconda3/bin:$PATH
  PATH=$HOME/bin:$PATH
fi

export LANG=en_US.utf8
export LC_ALL=en_US.utf8
export DOTFILES=$HOME/.dotfiles
export ZSH=$HOME/.oh-my-zsh
export PATH=$HOME/local/bin:$PATH

ZSH_THEME="typewritten"
HISTSIZE=1000
SAVEHIST=1000
plugins=(
    zsh-autosuggestions
    git
    zsh-syntax-highlighting
    tmux
    web-search
)

source $ZSH/oh-my-zsh.sh
source $DOTFILES/zsh/aliases.zsh
source $DOTFILES/zsh/ts.zsh
source $DOTFILES/zsh/conda.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

